#
# Autogenerated by generate-bytecode-expectations.
#

---
wrap: no
test function name: test

---
snippet: "
  var test;
  (function () {
    var a = {b: {bb: 2}, c: 3};
    function foo() {a.b.bb = a.c;}
    foo();
    test = foo;
  })();
"
frame size: 2
parameter count: 1
bytecode array length: 18
bytecodes: [
  /*   73 S> */ B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star0),
  /*   75 E> */ B(GetNamedProperty), R(0), U8(0), U8(0),
                B(Star1),
  /*   84 E> */ B(GetNamedProperty), R(0), U8(1), U8(2),
  /*   80 E> */ B(SetNamedProperty), R(1), U8(2), U8(4),
                B(LdaUndefined),
  /*   86 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["b"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["c"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["bb"],
]
handlers: [
]

---
snippet: "
  var test;
  (function () {
    var a = {b: {bb: 2}, c: function() {return 3}};
    function foo() {a.b.bb = a.c();}
    foo();
    test = foo;
  })();
"
frame size: 3
parameter count: 1
bytecode array length: 23
bytecodes: [
  /*   93 S> */ B(LdaImmutableCurrentContextSlot), U8(2),
                B(Star0),
  /*   95 E> */ B(GetNamedProperty), R(0), U8(0), U8(0),
                B(Star1),
  /*  104 E> */ B(GetNamedProperty), R(0), U8(1), U8(2),
                B(Star2),
  /*  104 E> */ B(CallProperty0), R(2), R(0), U8(4),
  /*  100 E> */ B(SetNamedProperty), R(1), U8(2), U8(6),
                B(LdaUndefined),
  /*  108 S> */ B(Return),
]
constant pool: [
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["b"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["c"],
  ONE_BYTE_INTERNALIZED_STRING_TYPE ["bb"],
]
handlers: [
]

