// Copyright 2022 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by `tools/dev/gen-static-roots.py`. Do
// not edit manually.

#ifndef V8_ROOTS_STATIC_ROOTS_H_
#define V8_ROOTS_STATIC_ROOTS_H_

#include "src/common/globals.h"

#if V8_STATIC_ROOTS_BOOL

// Disabling Wasm or Intl invalidates the contents of static-roots.h.
// TODO(olivf): To support static roots for multiple build configurations we
//              will need to generate target specific versions of this file.
static_assert(V8_ENABLE_WEBASSEMBLY);
static_assert(V8_INTL_SUPPORT);

namespace v8 {
namespace internal {

struct kStaticReadOnlyRoot {
  static constexpr Tagged_t free_space_map = 0x3225;
  static constexpr Tagged_t one_pointer_filler_map = 0x3895;
  static constexpr Tagged_t two_pointer_filler_map = 0x38bd;
  static constexpr Tagged_t uninitialized_value = 0x7b09;
  static constexpr Tagged_t undefined_value = 0x22d1;
  static constexpr Tagged_t the_hole_value = 0x22ed;
  static constexpr Tagged_t null_value = 0x22b5;
  static constexpr Tagged_t true_value = 0x3f31;
  static constexpr Tagged_t false_value = 0x3f4d;
  static constexpr Tagged_t empty_string = 0x542d;
  static constexpr Tagged_t meta_map = 0x2131;
  static constexpr Tagged_t byte_array_map = 0x31d5;
  static constexpr Tagged_t fixed_array_map = 0x2159;
  static constexpr Tagged_t fixed_cow_array_map = 0x21d1;
  static constexpr Tagged_t hash_table_map = 0x3985;
  static constexpr Tagged_t symbol_map = 0x2b6d;
  static constexpr Tagged_t one_byte_string_map = 0x2d9d;
  static constexpr Tagged_t one_byte_internalized_string_map = 0x2f2d;
  static constexpr Tagged_t scope_info_map = 0x2aa5;
  static constexpr Tagged_t shared_function_info_map = 0x3cf5;
  static constexpr Tagged_t code_map = 0x3815;
  static constexpr Tagged_t cell_map = 0x383d;
  static constexpr Tagged_t global_property_cell_map = 0x386d;
  static constexpr Tagged_t foreign_map = 0x2b95;
  static constexpr Tagged_t heap_number_map = 0x2b45;
  static constexpr Tagged_t transition_array_map = 0x395d;
  static constexpr Tagged_t thin_one_byte_string_map = 0x301d;
  static constexpr Tagged_t feedback_vector_map = 0x2b1d;
  static constexpr Tagged_t empty_scope_info = 0x3f09;
  static constexpr Tagged_t empty_fixed_array = 0x2299;
  static constexpr Tagged_t empty_descriptor_array = 0x2a95;
  static constexpr Tagged_t arguments_marker = 0x7b41;
  static constexpr Tagged_t exception = 0x7bb9;
  static constexpr Tagged_t termination_exception = 0x7b79;
  static constexpr Tagged_t optimized_out = 0x7bd5;
  static constexpr Tagged_t stale_register = 0x7c0d;
  static constexpr Tagged_t script_context_table_map = 0x3bb5;
  static constexpr Tagged_t closure_feedback_cell_array_map = 0x2af5;
  static constexpr Tagged_t feedback_metadata_map = 0x31ad;
  static constexpr Tagged_t array_list_map = 0x3b8d;
  static constexpr Tagged_t bigint_map = 0x2d4d;
  static constexpr Tagged_t object_boilerplate_description_map = 0x3bdd;
  static constexpr Tagged_t bytecode_array_map = 0x31fd;
  static constexpr Tagged_t code_data_container_map = 0x3d6d;
  static constexpr Tagged_t coverage_info_map = 0x3c05;
  static constexpr Tagged_t fixed_double_array_map = 0x3185;
  static constexpr Tagged_t global_dictionary_map = 0x3a75;
  static constexpr Tagged_t many_closures_cell_map = 0x3935;
  static constexpr Tagged_t mega_dom_handler_map = 0x2bbd;
  static constexpr Tagged_t module_info_map = 0x2acd;
  static constexpr Tagged_t name_dictionary_map = 0x3a25;
  static constexpr Tagged_t no_closures_cell_map = 0x38e5;
  static constexpr Tagged_t number_dictionary_map = 0x3a9d;
  static constexpr Tagged_t one_closure_cell_map = 0x390d;
  static constexpr Tagged_t ordered_hash_map_map = 0x39ad;
  static constexpr Tagged_t ordered_hash_set_map = 0x39d5;
  static constexpr Tagged_t name_to_index_hash_table_map = 0x3aed;
  static constexpr Tagged_t registered_symbol_table_map = 0x3b15;
  static constexpr Tagged_t ordered_name_dictionary_map = 0x39fd;
  static constexpr Tagged_t preparse_data_map = 0x3ccd;
  static constexpr Tagged_t property_array_map = 0x324d;
  static constexpr Tagged_t accessor_info_map = 0x3c2d;
  static constexpr Tagged_t side_effect_call_handler_info_map = 0x3c55;
  static constexpr Tagged_t side_effect_free_call_handler_info_map = 0x3c7d;
  static constexpr Tagged_t next_call_side_effect_free_call_handler_info_map =
      0x3ca5;
  static constexpr Tagged_t simple_number_dictionary_map = 0x3ac5;
  static constexpr Tagged_t small_ordered_hash_map_map = 0x3275;
  static constexpr Tagged_t small_ordered_hash_set_map = 0x329d;
  static constexpr Tagged_t small_ordered_name_dictionary_map = 0x32c5;
  static constexpr Tagged_t source_text_module_map = 0x3d1d;
  static constexpr Tagged_t swiss_name_dictionary_map = 0x3a4d;
  static constexpr Tagged_t synthetic_module_map = 0x3d45;
  static constexpr Tagged_t wasm_api_function_ref_map = 0x3d95;
  static constexpr Tagged_t wasm_capi_function_data_map = 0x3dbd;
  static constexpr Tagged_t wasm_exported_function_data_map = 0x3de5;
  static constexpr Tagged_t wasm_internal_function_map = 0x3e0d;
  static constexpr Tagged_t wasm_js_function_data_map = 0x3e35;
  static constexpr Tagged_t wasm_resume_data_map = 0x3e5d;
  static constexpr Tagged_t wasm_type_info_map = 0x3e85;
  static constexpr Tagged_t wasm_continuation_object_map = 0x3ead;
  static constexpr Tagged_t weak_fixed_array_map = 0x2181;
  static constexpr Tagged_t weak_array_list_map = 0x21a9;
  static constexpr Tagged_t ephemeron_hash_table_map = 0x3b65;
  static constexpr Tagged_t embedder_data_array_map = 0x3b3d;
  static constexpr Tagged_t weak_cell_map = 0x3ed5;
  static constexpr Tagged_t string_map = 0x2d75;
  static constexpr Tagged_t cons_one_byte_string_map = 0x2ded;
  static constexpr Tagged_t cons_string_map = 0x2dc5;
  static constexpr Tagged_t thin_string_map = 0x2ff5;
  static constexpr Tagged_t sliced_string_map = 0x2e15;
  static constexpr Tagged_t sliced_one_byte_string_map = 0x2e3d;
  static constexpr Tagged_t external_string_map = 0x2e65;
  static constexpr Tagged_t external_one_byte_string_map = 0x2e8d;
  static constexpr Tagged_t uncached_external_string_map = 0x2eb5;
  static constexpr Tagged_t internalized_string_map = 0x2f05;
  static constexpr Tagged_t external_internalized_string_map = 0x2f55;
  static constexpr Tagged_t external_one_byte_internalized_string_map = 0x2f7d;
  static constexpr Tagged_t uncached_external_internalized_string_map = 0x2fa5;
  static constexpr Tagged_t uncached_external_one_byte_internalized_string_map =
      0x2fcd;
  static constexpr Tagged_t uncached_external_one_byte_string_map = 0x2edd;
  static constexpr Tagged_t shared_one_byte_string_map = 0x306d;
  static constexpr Tagged_t shared_string_map = 0x3045;
  static constexpr Tagged_t shared_external_one_byte_string_map = 0x30bd;
  static constexpr Tagged_t shared_external_string_map = 0x3095;
  static constexpr Tagged_t shared_uncached_external_one_byte_string_map =
      0x310d;
  static constexpr Tagged_t shared_uncached_external_string_map = 0x30e5;
  static constexpr Tagged_t shared_thin_one_byte_string_map = 0x315d;
  static constexpr Tagged_t shared_thin_string_map = 0x3135;
  static constexpr Tagged_t undefined_map = 0x2221;
  static constexpr Tagged_t the_hole_map = 0x2271;
  static constexpr Tagged_t null_map = 0x2249;
  static constexpr Tagged_t boolean_map = 0x2be5;
  static constexpr Tagged_t uninitialized_map = 0x2c0d;
  static constexpr Tagged_t arguments_marker_map = 0x2c35;
  static constexpr Tagged_t exception_map = 0x2c5d;
  static constexpr Tagged_t termination_exception_map = 0x2c85;
  static constexpr Tagged_t optimized_out_map = 0x2cad;
  static constexpr Tagged_t stale_register_map = 0x2cd5;
  static constexpr Tagged_t self_reference_marker_map = 0x2cfd;
  static constexpr Tagged_t basic_block_counters_marker_map = 0x2d25;
  static constexpr Tagged_t empty_enum_cache = 0x2a89;
  static constexpr Tagged_t empty_property_array = 0x3f71;
  static constexpr Tagged_t empty_byte_array = 0x3f69;
  static constexpr Tagged_t empty_object_boilerplate_description = 0x3f19;
  static constexpr Tagged_t empty_array_boilerplate_description = 0x3f25;
  static constexpr Tagged_t empty_closure_feedback_cell_array = 0x3f79;
  static constexpr Tagged_t empty_slow_element_dictionary = 0x81fd;
  static constexpr Tagged_t empty_ordered_hash_map = 0x8221;
  static constexpr Tagged_t empty_ordered_hash_set = 0x8235;
  static constexpr Tagged_t empty_feedback_metadata = 0x828d;
  static constexpr Tagged_t empty_property_dictionary = 0x81b9;
  static constexpr Tagged_t empty_ordered_property_dictionary = 0x8249;
  static constexpr Tagged_t empty_swiss_property_dictionary = 0x826d;
  static constexpr Tagged_t noop_interceptor_info = 0x3f81;
  static constexpr Tagged_t empty_array_list = 0x3efd;
  static constexpr Tagged_t empty_weak_fixed_array = 0x22a1;
  static constexpr Tagged_t empty_weak_array_list = 0x22a9;
  static constexpr Tagged_t invalid_prototype_validity_cell = 0x3865;
  static constexpr Tagged_t nan_value = 0x3fb5;
  static constexpr Tagged_t hole_nan_value = 0x3fc1;
  static constexpr Tagged_t infinity_value = 0x3fcd;
  static constexpr Tagged_t minus_zero_value = 0x3fa9;
  static constexpr Tagged_t minus_infinity_value = 0x3fd9;
  static constexpr Tagged_t max_safe_integer = 0x3fe5;
  static constexpr Tagged_t max_uint_32 = 0x3ff1;
  static constexpr Tagged_t smi_min_value = 0x3ffd;
  static constexpr Tagged_t smi_max_value_plus_one = 0x4009;
  static constexpr Tagged_t single_character_string_table = 0x4025;
  static constexpr Tagged_t self_reference_marker = 0x7c45;
  static constexpr Tagged_t basic_block_counters_marker = 0x7c85;
  static constexpr Tagged_t off_heap_trampoline_relocation_info = 0x830d;
  static constexpr Tagged_t trampoline_trivial_code_data_container = 0x22d1;
  static constexpr Tagged_t trampoline_promise_rejection_code_data_container =
      0x22d1;
  static constexpr Tagged_t global_this_binding_scope_info = 0x8299;
  static constexpr Tagged_t empty_function_scope_info = 0x82b9;
  static constexpr Tagged_t native_scope_info = 0x82dd;
  static constexpr Tagged_t shadow_realm_scope_info = 0x82f5;
  static constexpr Tagged_t empty_symbol_table = 0x81e1;
  static constexpr Tagged_t hash_seed = 0x4015;
  static constexpr Tagged_t adoptText_string = 0x5439;
  static constexpr Tagged_t approximatelySign_string = 0x5451;
  static constexpr Tagged_t baseName_string = 0x5471;
  static constexpr Tagged_t accounting_string = 0x5485;
  static constexpr Tagged_t breakType_string = 0x549d;
  static constexpr Tagged_t calendars_string = 0x54b5;
  static constexpr Tagged_t cardinal_string = 0x54cd;
  static constexpr Tagged_t caseFirst_string = 0x54e1;
  static constexpr Tagged_t ceil_string = 0x54f9;
  static constexpr Tagged_t compare_string = 0x5509;
  static constexpr Tagged_t collation_string = 0x551d;
  static constexpr Tagged_t collations_string = 0x5535;
  static constexpr Tagged_t compact_string = 0x554d;
  static constexpr Tagged_t compactDisplay_string = 0x5561;
  static constexpr Tagged_t currency_string = 0x557d;
  static constexpr Tagged_t currencyDisplay_string = 0x5591;
  static constexpr Tagged_t currencySign_string = 0x55ad;
  static constexpr Tagged_t dateStyle_string = 0x55c5;
  static constexpr Tagged_t dateTimeField_string = 0x55dd;
  static constexpr Tagged_t dayPeriod_string = 0x55f9;
  static constexpr Tagged_t daysDisplay_string = 0x5611;
  static constexpr Tagged_t decimal_string = 0x5629;
  static constexpr Tagged_t dialect_string = 0x563d;
  static constexpr Tagged_t digital_string = 0x5651;
  static constexpr Tagged_t direction_string = 0x5665;
  static constexpr Tagged_t endRange_string = 0x567d;
  static constexpr Tagged_t engineering_string = 0x5691;
  static constexpr Tagged_t exceptZero_string = 0x56a9;
  static constexpr Tagged_t expand_string = 0x56c1;
  static constexpr Tagged_t exponentInteger_string = 0x56d5;
  static constexpr Tagged_t exponentMinusSign_string = 0x56f1;
  static constexpr Tagged_t exponentSeparator_string = 0x5711;
  static constexpr Tagged_t fallback_string = 0x5731;
  static constexpr Tagged_t first_string = 0x5745;
  static constexpr Tagged_t firstDay_string = 0x5759;
  static constexpr Tagged_t floor_string = 0x576d;
  static constexpr Tagged_t format_string = 0x5781;
  static constexpr Tagged_t fraction_string = 0x5795;
  static constexpr Tagged_t fractionalDigits_string = 0x57a9;
  static constexpr Tagged_t fractionalSecond_string = 0x57c5;
  static constexpr Tagged_t full_string = 0x57e1;
  static constexpr Tagged_t granularity_string = 0x57f1;
  static constexpr Tagged_t grapheme_string = 0x5809;
  static constexpr Tagged_t group_string = 0x581d;
  static constexpr Tagged_t h11_string = 0x5831;
  static constexpr Tagged_t h12_string = 0x5841;
  static constexpr Tagged_t h23_string = 0x5851;
  static constexpr Tagged_t h24_string = 0x5861;
  static constexpr Tagged_t halfCeil_string = 0x5871;
  static constexpr Tagged_t halfEven_string = 0x5885;
  static constexpr Tagged_t halfExpand_string = 0x5899;
  static constexpr Tagged_t halfFloor_string = 0x58b1;
  static constexpr Tagged_t halfTrunc_string = 0x58c9;
  static constexpr Tagged_t hour12_string = 0x58e1;
  static constexpr Tagged_t hourCycle_string = 0x58f5;
  static constexpr Tagged_t hourCycles_string = 0x590d;
  static constexpr Tagged_t hoursDisplay_string = 0x5925;
  static constexpr Tagged_t ideo_string = 0x593d;
  static constexpr Tagged_t ignorePunctuation_string = 0x594d;
  static constexpr Tagged_t Invalid_Date_string = 0x596d;
  static constexpr Tagged_t integer_string = 0x5985;
  static constexpr Tagged_t isWordLike_string = 0x5999;
  static constexpr Tagged_t kana_string = 0x59b1;
  static constexpr Tagged_t language_string = 0x59c1;
  static constexpr Tagged_t languageDisplay_string = 0x59d5;
  static constexpr Tagged_t lessPrecision_string = 0x59f1;
  static constexpr Tagged_t letter_string = 0x5a0d;
  static constexpr Tagged_t list_string = 0x5a21;
  static constexpr Tagged_t literal_string = 0x5a31;
  static constexpr Tagged_t locale_string = 0x5a45;
  static constexpr Tagged_t loose_string = 0x5a59;
  static constexpr Tagged_t lower_string = 0x5a6d;
  static constexpr Tagged_t ltr_string = 0x5a81;
  static constexpr Tagged_t maximumFractionDigits_string = 0x5a91;
  static constexpr Tagged_t maximumSignificantDigits_string = 0x5ab5;
  static constexpr Tagged_t microsecondsDisplay_string = 0x5ad9;
  static constexpr Tagged_t millisecondsDisplay_string = 0x5af9;
  static constexpr Tagged_t min2_string = 0x5b19;
  static constexpr Tagged_t minimalDays_string = 0x5b29;
  static constexpr Tagged_t minimumFractionDigits_string = 0x5b41;
  static constexpr Tagged_t minimumIntegerDigits_string = 0x5b65;
  static constexpr Tagged_t minimumSignificantDigits_string = 0x5b85;
  static constexpr Tagged_t minus_0 = 0x5ba9;
  static constexpr Tagged_t minusSign_string = 0x5bb9;
  static constexpr Tagged_t minutesDisplay_string = 0x5bd1;
  static constexpr Tagged_t monthsDisplay_string = 0x5bed;
  static constexpr Tagged_t morePrecision_string = 0x5c09;
  static constexpr Tagged_t nan_string = 0x5c25;
  static constexpr Tagged_t nanosecondsDisplay_string = 0x5c35;
  static constexpr Tagged_t narrowSymbol_string = 0x5c55;
  static constexpr Tagged_t negative_string = 0x5c6d;
  static constexpr Tagged_t never_string = 0x5c81;
  static constexpr Tagged_t none_string = 0x5c95;
  static constexpr Tagged_t notation_string = 0x5ca5;
  static constexpr Tagged_t normal_string = 0x5cb9;
  static constexpr Tagged_t numberingSystem_string = 0x5ccd;
  static constexpr Tagged_t numberingSystems_string = 0x5ce9;
  static constexpr Tagged_t numeric_string = 0x5d05;
  static constexpr Tagged_t ordinal_string = 0x5d19;
  static constexpr Tagged_t percentSign_string = 0x5d2d;
  static constexpr Tagged_t plusSign_string = 0x5d45;
  static constexpr Tagged_t quarter_string = 0x5d59;
  static constexpr Tagged_t region_string = 0x5d6d;
  static constexpr Tagged_t relatedYear_string = 0x5d81;
  static constexpr Tagged_t roundingMode_string = 0x5d99;
  static constexpr Tagged_t roundingPriority_string = 0x5db1;
  static constexpr Tagged_t rtl_string = 0x5dcd;
  static constexpr Tagged_t scientific_string = 0x5ddd;
  static constexpr Tagged_t secondsDisplay_string = 0x5df5;
  static constexpr Tagged_t segment_string = 0x5e11;
  static constexpr Tagged_t SegmentIterator_string = 0x5e25;
  static constexpr Tagged_t Segments_string = 0x5e41;
  static constexpr Tagged_t sensitivity_string = 0x5e55;
  static constexpr Tagged_t sep_string = 0x5e6d;
  static constexpr Tagged_t shared_string = 0x5e7d;
  static constexpr Tagged_t signDisplay_string = 0x5e91;
  static constexpr Tagged_t standard_string = 0x5ea9;
  static constexpr Tagged_t startRange_string = 0x5ebd;
  static constexpr Tagged_t strict_string = 0x5ed5;
  static constexpr Tagged_t stripIfInteger_string = 0x5ee9;
  static constexpr Tagged_t style_string = 0x5f05;
  static constexpr Tagged_t term_string = 0x5f19;
  static constexpr Tagged_t textInfo_string = 0x5f29;
  static constexpr Tagged_t timeStyle_string = 0x5f3d;
  static constexpr Tagged_t timeZones_string = 0x5f55;
  static constexpr Tagged_t timeZoneName_string = 0x5f6d;
  static constexpr Tagged_t trailingZeroDisplay_string = 0x5f85;
  static constexpr Tagged_t trunc_string = 0x5fa5;
  static constexpr Tagged_t two_digit_string = 0x5fb9;
  static constexpr Tagged_t type_string = 0x5fcd;
  static constexpr Tagged_t unknown_string = 0x5fdd;
  static constexpr Tagged_t upper_string = 0x5ff1;
  static constexpr Tagged_t usage_string = 0x6005;
  static constexpr Tagged_t useGrouping_string = 0x6019;
  static constexpr Tagged_t unitDisplay_string = 0x6031;
  static constexpr Tagged_t weekday_string = 0x6049;
  static constexpr Tagged_t weekend_string = 0x605d;
  static constexpr Tagged_t weeksDisplay_string = 0x6071;
  static constexpr Tagged_t weekInfo_string = 0x6089;
  static constexpr Tagged_t yearName_string = 0x609d;
  static constexpr Tagged_t yearsDisplay_string = 0x60b1;
  static constexpr Tagged_t add_string = 0x60c9;
  static constexpr Tagged_t AggregateError_string = 0x60d9;
  static constexpr Tagged_t always_string = 0x60f5;
  static constexpr Tagged_t anonymous_function_string = 0x6109;
  static constexpr Tagged_t anonymous_string = 0x6129;
  static constexpr Tagged_t apply_string = 0x6141;
  static constexpr Tagged_t Arguments_string = 0x6155;
  static constexpr Tagged_t arguments_string = 0x616d;
  static constexpr Tagged_t arguments_to_string = 0x6185;
  static constexpr Tagged_t Array_string = 0x61a5;
  static constexpr Tagged_t array_to_string = 0x61b9;
  static constexpr Tagged_t ArrayBuffer_string = 0x61d5;
  static constexpr Tagged_t ArrayIterator_string = 0x61ed;
  static constexpr Tagged_t as_string = 0x6209;
  static constexpr Tagged_t assert_string = 0x6219;
  static constexpr Tagged_t async_string = 0x622d;
  static constexpr Tagged_t AtomicsCondition_string = 0x6241;
  static constexpr Tagged_t AtomicsMutex_string = 0x6261;
  static constexpr Tagged_t auto_string = 0x627d;
  static constexpr Tagged_t await_string = 0x628d;
  static constexpr Tagged_t BigInt_string = 0x62a1;
  static constexpr Tagged_t bigint_string = 0x62b5;
  static constexpr Tagged_t BigInt64Array_string = 0x62c9;
  static constexpr Tagged_t BigUint64Array_string = 0x62e5;
  static constexpr Tagged_t bind_string = 0x6301;
  static constexpr Tagged_t blank_string = 0x6311;
  static constexpr Tagged_t Boolean_string = 0x6325;
  static constexpr Tagged_t boolean_string = 0x6339;
  static constexpr Tagged_t boolean_to_string = 0x634d;
  static constexpr Tagged_t bound__string = 0x6369;
  static constexpr Tagged_t buffer_string = 0x637d;
  static constexpr Tagged_t byte_length_string = 0x6391;
  static constexpr Tagged_t byte_offset_string = 0x63a9;
  static constexpr Tagged_t CompileError_string = 0x63c1;
  static constexpr Tagged_t calendar_string = 0x63d9;
  static constexpr Tagged_t callee_string = 0x63ed;
  static constexpr Tagged_t caller_string = 0x6401;
  static constexpr Tagged_t cause_string = 0x6415;
  static constexpr Tagged_t character_string = 0x6429;
  static constexpr Tagged_t closure_string = 0x6441;
  static constexpr Tagged_t code_string = 0x6459;
  static constexpr Tagged_t column_string = 0x6469;
  static constexpr Tagged_t computed_string = 0x647d;
  static constexpr Tagged_t configurable_string = 0x6495;
  static constexpr Tagged_t conjunction_string = 0x64ad;
  static constexpr Tagged_t console_string = 0x64c5;
  static constexpr Tagged_t constrain_string = 0x64d9;
  static constexpr Tagged_t construct_string = 0x64f1;
  static constexpr Tagged_t current_string = 0x6509;
  static constexpr Tagged_t Date_string = 0x651d;
  static constexpr Tagged_t date_to_string = 0x652d;
  static constexpr Tagged_t dateAdd_string = 0x6549;
  static constexpr Tagged_t dateFromFields_string = 0x655d;
  static constexpr Tagged_t dateUntil_string = 0x6579;
  static constexpr Tagged_t day_string = 0x6591;
  static constexpr Tagged_t dayOfWeek_string = 0x65a1;
  static constexpr Tagged_t dayOfYear_string = 0x65b9;
  static constexpr Tagged_t days_string = 0x65d1;
  static constexpr Tagged_t daysInMonth_string = 0x65e1;
  static constexpr Tagged_t daysInWeek_string = 0x65f9;
  static constexpr Tagged_t daysInYear_string = 0x6611;
  static constexpr Tagged_t default_string = 0x6629;
  static constexpr Tagged_t defineProperty_string = 0x663d;
  static constexpr Tagged_t deleteProperty_string = 0x6659;
  static constexpr Tagged_t disjunction_string = 0x6675;
  static constexpr Tagged_t done_string = 0x668d;
  static constexpr Tagged_t dot_brand_string = 0x669d;
  static constexpr Tagged_t dot_catch_string = 0x66b1;
  static constexpr Tagged_t dot_default_string = 0x66c5;
  static constexpr Tagged_t dot_for_string = 0x66d9;
  static constexpr Tagged_t dot_generator_object_string = 0x66e9;
  static constexpr Tagged_t dot_home_object_string = 0x6709;
  static constexpr Tagged_t dot_new_target_string = 0x6721;
  static constexpr Tagged_t dot_result_string = 0x6739;
  static constexpr Tagged_t dot_repl_result_string = 0x674d;
  static constexpr Tagged_t dot_static_home_object_string = 0x6765;
  static constexpr Tagged_t dot_string = 0x470d;
  static constexpr Tagged_t dot_switch_tag_string = 0x6785;
  static constexpr Tagged_t dotAll_string = 0x679d;
  static constexpr Tagged_t Error_string = 0x67b1;
  static constexpr Tagged_t EvalError_string = 0x67c5;
  static constexpr Tagged_t enumerable_string = 0x67dd;
  static constexpr Tagged_t element_string = 0x67f5;
  static constexpr Tagged_t epochMicroseconds_string = 0x6809;
  static constexpr Tagged_t epochMilliseconds_string = 0x6829;
  static constexpr Tagged_t epochNanoseconds_string = 0x6849;
  static constexpr Tagged_t epochSeconds_string = 0x6865;
  static constexpr Tagged_t era_string = 0x687d;
  static constexpr Tagged_t eraYear_string = 0x688d;
  static constexpr Tagged_t errors_string = 0x68a1;
  static constexpr Tagged_t error_to_string = 0x68b5;
  static constexpr Tagged_t eval_string = 0x68d1;
  static constexpr Tagged_t exception_string = 0x68e1;
  static constexpr Tagged_t exec_string = 0x68f9;
  static constexpr Tagged_t false_string = 0x6909;
  static constexpr Tagged_t fields_string = 0x691d;
  static constexpr Tagged_t FinalizationRegistry_string = 0x6931;
  static constexpr Tagged_t flags_string = 0x6951;
  static constexpr Tagged_t Float32Array_string = 0x6965;
  static constexpr Tagged_t Float64Array_string = 0x697d;
  static constexpr Tagged_t fractionalSecondDigits_string = 0x6995;
  static constexpr Tagged_t from_string = 0x69b9;
  static constexpr Tagged_t Function_string = 0x69c9;
  static constexpr Tagged_t function_native_code_string = 0x69dd;
  static constexpr Tagged_t function_string = 0x6a09;
  static constexpr Tagged_t function_to_string = 0x6a1d;
  static constexpr Tagged_t Generator_string = 0x6a3d;
  static constexpr Tagged_t get_space_string = 0x6a55;
  static constexpr Tagged_t get_string = 0x6a65;
  static constexpr Tagged_t getOffsetNanosecondsFor_string = 0x6a75;
  static constexpr Tagged_t getOwnPropertyDescriptor_string = 0x6a99;
  static constexpr Tagged_t getPossibleInstantsFor_string = 0x6abd;
  static constexpr Tagged_t getPrototypeOf_string = 0x6ae1;
  static constexpr Tagged_t global_string = 0x6afd;
  static constexpr Tagged_t globalThis_string = 0x6b11;
  static constexpr Tagged_t groups_string = 0x6b29;
  static constexpr Tagged_t growable_string = 0x6b3d;
  static constexpr Tagged_t has_string = 0x6b51;
  static constexpr Tagged_t hasIndices_string = 0x6b61;
  static constexpr Tagged_t hour_string = 0x6b79;
  static constexpr Tagged_t hours_string = 0x6b89;
  static constexpr Tagged_t hoursInDay_string = 0x6b9d;
  static constexpr Tagged_t ignoreCase_string = 0x6bb5;
  static constexpr Tagged_t id_string = 0x6bcd;
  static constexpr Tagged_t illegal_access_string = 0x6bdd;
  static constexpr Tagged_t illegal_argument_string = 0x6bf9;
  static constexpr Tagged_t inLeapYear_string = 0x6c15;
  static constexpr Tagged_t index_string = 0x6c2d;
  static constexpr Tagged_t indices_string = 0x6c41;
  static constexpr Tagged_t Infinity_string = 0x6c55;
  static constexpr Tagged_t infinity_string = 0x6c69;
  static constexpr Tagged_t input_string = 0x6c7d;
  static constexpr Tagged_t Int16Array_string = 0x6c91;
  static constexpr Tagged_t Int32Array_string = 0x6ca9;
  static constexpr Tagged_t Int8Array_string = 0x6cc1;
  static constexpr Tagged_t isExtensible_string = 0x6cd9;
  static constexpr Tagged_t iso8601_string = 0x6cf1;
  static constexpr Tagged_t isoDay_string = 0x6d05;
  static constexpr Tagged_t isoHour_string = 0x6d19;
  static constexpr Tagged_t isoMicrosecond_string = 0x6d2d;
  static constexpr Tagged_t isoMillisecond_string = 0x6d49;
  static constexpr Tagged_t isoMinute_string = 0x6d65;
  static constexpr Tagged_t isoMonth_string = 0x6d7d;
  static constexpr Tagged_t isoNanosecond_string = 0x6d91;
  static constexpr Tagged_t isoSecond_string = 0x6dad;
  static constexpr Tagged_t isoYear_string = 0x6dc5;
  static constexpr Tagged_t jsMemoryEstimate_string = 0x6dd9;
  static constexpr Tagged_t jsMemoryRange_string = 0x6df5;
  static constexpr Tagged_t keys_string = 0x6e11;
  static constexpr Tagged_t largestUnit_string = 0x6e21;
  static constexpr Tagged_t lastIndex_string = 0x6e39;
  static constexpr Tagged_t length_string = 0x6e51;
  static constexpr Tagged_t let_string = 0x6e65;
  static constexpr Tagged_t line_string = 0x6e75;
  static constexpr Tagged_t linear_string = 0x6e85;
  static constexpr Tagged_t LinkError_string = 0x6e99;
  static constexpr Tagged_t long_string = 0x6eb1;
  static constexpr Tagged_t Map_string = 0x6ec1;
  static constexpr Tagged_t MapIterator_string = 0x6ed1;
  static constexpr Tagged_t max_byte_length_string = 0x6ee9;
  static constexpr Tagged_t medium_string = 0x6f05;
  static constexpr Tagged_t mergeFields_string = 0x6f19;
  static constexpr Tagged_t message_string = 0x6f31;
  static constexpr Tagged_t meta_string = 0x6f45;
  static constexpr Tagged_t minus_Infinity_string = 0x6f55;
  static constexpr Tagged_t microsecond_string = 0x6f6d;
  static constexpr Tagged_t microseconds_string = 0x6f85;
  static constexpr Tagged_t millisecond_string = 0x6f9d;
  static constexpr Tagged_t milliseconds_string = 0x6fb5;
  static constexpr Tagged_t minute_string = 0x6fcd;
  static constexpr Tagged_t minutes_string = 0x6fe1;
  static constexpr Tagged_t Module_string = 0x6ff5;
  static constexpr Tagged_t month_string = 0x7009;
  static constexpr Tagged_t monthDayFromFields_string = 0x701d;
  static constexpr Tagged_t months_string = 0x703d;
  static constexpr Tagged_t monthsInYear_string = 0x7051;
  static constexpr Tagged_t monthCode_string = 0x7069;
  static constexpr Tagged_t multiline_string = 0x7081;
  static constexpr Tagged_t name_string = 0x7099;
  static constexpr Tagged_t NaN_string = 0x70a9;
  static constexpr Tagged_t nanosecond_string = 0x70b9;
  static constexpr Tagged_t nanoseconds_string = 0x70d1;
  static constexpr Tagged_t narrow_string = 0x70e9;
  static constexpr Tagged_t native_string = 0x70fd;
  static constexpr Tagged_t new_target_string = 0x6721;
  static constexpr Tagged_t NFC_string = 0x7111;
  static constexpr Tagged_t NFD_string = 0x7121;
  static constexpr Tagged_t NFKC_string = 0x7131;
  static constexpr Tagged_t NFKD_string = 0x7141;
  static constexpr Tagged_t not_equal_string = 0x7151;
  static constexpr Tagged_t null_string = 0x7169;
  static constexpr Tagged_t null_to_string = 0x7179;
  static constexpr Tagged_t Number_string = 0x7195;
  static constexpr Tagged_t number_string = 0x71a9;
  static constexpr Tagged_t number_to_string = 0x71bd;
  static constexpr Tagged_t Object_string = 0x71d9;
  static constexpr Tagged_t object_string = 0x71ed;
  static constexpr Tagged_t object_to_string = 0x7201;
  static constexpr Tagged_t of_string = 0x721d;
  static constexpr Tagged_t offset_string = 0x722d;
  static constexpr Tagged_t offsetNanoseconds_string = 0x7241;
  static constexpr Tagged_t ok_string = 0x7261;
  static constexpr Tagged_t one_string = 0x473d;
  static constexpr Tagged_t other_string = 0x7271;
  static constexpr Tagged_t overflow_string = 0x7285;
  static constexpr Tagged_t ownKeys_string = 0x7299;
  static constexpr Tagged_t percent_string = 0x72ad;
  static constexpr Tagged_t plainDate_string = 0x72c1;
  static constexpr Tagged_t plainTime_string = 0x72d9;
  static constexpr Tagged_t position_string = 0x72f1;
  static constexpr Tagged_t preventExtensions_string = 0x7305;
  static constexpr Tagged_t private_constructor_string = 0x7325;
  static constexpr Tagged_t Promise_string = 0x733d;
  static constexpr Tagged_t proto_string = 0x7351;
  static constexpr Tagged_t prototype_string = 0x7369;
  static constexpr Tagged_t proxy_string = 0x7381;
  static constexpr Tagged_t Proxy_string = 0x7395;
  static constexpr Tagged_t query_colon_string = 0x73a9;
  static constexpr Tagged_t RangeError_string = 0x73b9;
  static constexpr Tagged_t raw_json_string = 0x73d1;
  static constexpr Tagged_t raw_string = 0x73e5;
  static constexpr Tagged_t ReferenceError_string = 0x73f5;
  static constexpr Tagged_t ReflectGet_string = 0x7411;
  static constexpr Tagged_t ReflectHas_string = 0x7429;
  static constexpr Tagged_t RegExp_string = 0x7441;
  static constexpr Tagged_t regexp_to_string = 0x7455;
  static constexpr Tagged_t reject_string = 0x7471;
  static constexpr Tagged_t relativeTo_string = 0x7485;
  static constexpr Tagged_t resizable_string = 0x749d;
  static constexpr Tagged_t ResizableArrayBuffer_string = 0x74b5;
  static constexpr Tagged_t return_string = 0x74d5;
  static constexpr Tagged_t revoke_string = 0x74e9;
  static constexpr Tagged_t roundingIncrement_string = 0x74fd;
  static constexpr Tagged_t RuntimeError_string = 0x751d;
  static constexpr Tagged_t WebAssemblyException_string = 0x7535;
  static constexpr Tagged_t Script_string = 0x7559;
  static constexpr Tagged_t script_string = 0x756d;
  static constexpr Tagged_t second_string = 0x7581;
  static constexpr Tagged_t seconds_string = 0x7595;
  static constexpr Tagged_t short_string = 0x75a9;
  static constexpr Tagged_t Set_string = 0x75bd;
  static constexpr Tagged_t sentence_string = 0x75cd;
  static constexpr Tagged_t set_space_string = 0x75e1;
  static constexpr Tagged_t set_string = 0x75f1;
  static constexpr Tagged_t SetIterator_string = 0x7601;
  static constexpr Tagged_t setPrototypeOf_string = 0x7619;
  static constexpr Tagged_t ShadowRealm_string = 0x7635;
  static constexpr Tagged_t SharedArray_string = 0x764d;
  static constexpr Tagged_t SharedArrayBuffer_string = 0x7665;
  static constexpr Tagged_t SharedStruct_string = 0x7685;
  static constexpr Tagged_t sign_string = 0x769d;
  static constexpr Tagged_t smallestUnit_string = 0x76ad;
  static constexpr Tagged_t source_string = 0x76c5;
  static constexpr Tagged_t sourceText_string = 0x76d9;
  static constexpr Tagged_t stack_string = 0x76f1;
  static constexpr Tagged_t stackTraceLimit_string = 0x7705;
  static constexpr Tagged_t sticky_string = 0x7721;
  static constexpr Tagged_t String_string = 0x7735;
  static constexpr Tagged_t string_string = 0x7749;
  static constexpr Tagged_t string_to_string = 0x775d;
  static constexpr Tagged_t Symbol_iterator_string = 0x7779;
  static constexpr Tagged_t symbol_species_string = 0x7795;
  static constexpr Tagged_t Symbol_species_string = 0x77b1;
  static constexpr Tagged_t Symbol_string = 0x77cd;
  static constexpr Tagged_t symbol_string = 0x77e1;
  static constexpr Tagged_t SyntaxError_string = 0x77f5;
  static constexpr Tagged_t target_string = 0x780d;
  static constexpr Tagged_t this_function_string = 0x7821;
  static constexpr Tagged_t this_string = 0x783d;
  static constexpr Tagged_t throw_string = 0x784d;
  static constexpr Tagged_t timed_out_string = 0x7861;
  static constexpr Tagged_t timeZone_string = 0x7879;
  static constexpr Tagged_t toJSON_string = 0x788d;
  static constexpr Tagged_t toString_string = 0x78a1;
  static constexpr Tagged_t true_string = 0x78b5;
  static constexpr Tagged_t total_string = 0x78c5;
  static constexpr Tagged_t TypeError_string = 0x78d9;
  static constexpr Tagged_t Uint16Array_string = 0x78f1;
  static constexpr Tagged_t Uint32Array_string = 0x7909;
  static constexpr Tagged_t Uint8Array_string = 0x7921;
  static constexpr Tagged_t Uint8ClampedArray_string = 0x7939;
  static constexpr Tagged_t undefined_string = 0x7959;
  static constexpr Tagged_t undefined_to_string = 0x7971;
  static constexpr Tagged_t unicode_string = 0x7991;
  static constexpr Tagged_t unicodeSets_string = 0x79a5;
  static constexpr Tagged_t unit_string = 0x79bd;
  static constexpr Tagged_t URIError_string = 0x79cd;
  static constexpr Tagged_t UTC_string = 0x79e1;
  static constexpr Tagged_t value_string = 0x79f1;
  static constexpr Tagged_t valueOf_string = 0x7a05;
  static constexpr Tagged_t WeakMap_string = 0x7a19;
  static constexpr Tagged_t WeakRef_string = 0x7a2d;
  static constexpr Tagged_t WeakSet_string = 0x7a41;
  static constexpr Tagged_t week_string = 0x7a55;
  static constexpr Tagged_t weeks_string = 0x7a65;
  static constexpr Tagged_t weekOfYear_string = 0x7a79;
  static constexpr Tagged_t word_string = 0x7a91;
  static constexpr Tagged_t writable_string = 0x7aa1;
  static constexpr Tagged_t yearMonthFromFields_string = 0x7ab5;
  static constexpr Tagged_t year_string = 0x7ad5;
  static constexpr Tagged_t years_string = 0x7ae5;
  static constexpr Tagged_t zero_string = 0x472d;
  static constexpr Tagged_t array_buffer_wasm_memory_symbol = 0x7cc9;
  static constexpr Tagged_t call_site_info_symbol = 0x7cd9;
  static constexpr Tagged_t console_context_id_symbol = 0x7ce9;
  static constexpr Tagged_t console_context_name_symbol = 0x7cf9;
  static constexpr Tagged_t class_fields_symbol = 0x7d09;
  static constexpr Tagged_t class_positions_symbol = 0x7d19;
  static constexpr Tagged_t elements_transition_symbol = 0x7d29;
  static constexpr Tagged_t error_end_pos_symbol = 0x7d39;
  static constexpr Tagged_t error_script_symbol = 0x7d49;
  static constexpr Tagged_t error_stack_symbol = 0x7d59;
  static constexpr Tagged_t error_start_pos_symbol = 0x7d69;
  static constexpr Tagged_t frozen_symbol = 0x7d79;
  static constexpr Tagged_t interpreter_trampoline_symbol = 0x7d89;
  static constexpr Tagged_t mega_dom_symbol = 0x7d99;
  static constexpr Tagged_t megamorphic_symbol = 0x7da9;
  static constexpr Tagged_t native_context_index_symbol = 0x7db9;
  static constexpr Tagged_t nonextensible_symbol = 0x7dc9;
  static constexpr Tagged_t not_mapped_symbol = 0x7dd9;
  static constexpr Tagged_t promise_debug_marker_symbol = 0x7de9;
  static constexpr Tagged_t promise_debug_message_symbol = 0x7df9;
  static constexpr Tagged_t promise_forwarding_handler_symbol = 0x7e09;
  static constexpr Tagged_t promise_handled_by_symbol = 0x7e19;
  static constexpr Tagged_t promise_awaited_by_symbol = 0x7e29;
  static constexpr Tagged_t regexp_result_names_symbol = 0x7e39;
  static constexpr Tagged_t regexp_result_regexp_input_symbol = 0x7e49;
  static constexpr Tagged_t regexp_result_regexp_last_index_symbol = 0x7e59;
  static constexpr Tagged_t sealed_symbol = 0x7e69;
  static constexpr Tagged_t strict_function_transition_symbol = 0x7e79;
  static constexpr Tagged_t template_literal_function_literal_id_symbol =
      0x7e89;
  static constexpr Tagged_t template_literal_slot_id_symbol = 0x7e99;
  static constexpr Tagged_t wasm_exception_tag_symbol = 0x7ea9;
  static constexpr Tagged_t wasm_exception_values_symbol = 0x7eb9;
  static constexpr Tagged_t wasm_uncatchable_symbol = 0x7ec9;
  static constexpr Tagged_t wasm_wrapped_object_symbol = 0x7ed9;
  static constexpr Tagged_t wasm_debug_proxy_cache_symbol = 0x7ee9;
  static constexpr Tagged_t wasm_debug_proxy_names_symbol = 0x7ef9;
  static constexpr Tagged_t uninitialized_symbol = 0x7f09;
  static constexpr Tagged_t async_iterator_symbol = 0x7f19;
  static constexpr Tagged_t intl_fallback_symbol = 0x7f49;
  static constexpr Tagged_t match_all_symbol = 0x7f81;
  static constexpr Tagged_t match_symbol = 0x7fad;
  static constexpr Tagged_t replace_symbol = 0x7fd5;
  static constexpr Tagged_t search_symbol = 0x8001;
  static constexpr Tagged_t split_symbol = 0x802d;
  static constexpr Tagged_t to_primitive_symbol = 0x8055;
  static constexpr Tagged_t unscopables_symbol = 0x8085;
  static constexpr Tagged_t has_instance_symbol = 0x80b5;
  static constexpr Tagged_t to_string_tag_symbol = 0x80e5;
  static constexpr Tagged_t promise_fulfill_reaction_job_task_map = 0x2309;
  static constexpr Tagged_t promise_reject_reaction_job_task_map = 0x2331;
  static constexpr Tagged_t callable_task_map = 0x2359;
  static constexpr Tagged_t callback_task_map = 0x2381;
  static constexpr Tagged_t promise_resolve_thenable_job_task_map = 0x23a9;
  static constexpr Tagged_t function_template_info_map = 0x23d1;
  static constexpr Tagged_t object_template_info_map = 0x23f9;
  static constexpr Tagged_t access_check_info_map = 0x2421;
  static constexpr Tagged_t accessor_pair_map = 0x2449;
  static constexpr Tagged_t aliased_arguments_entry_map = 0x2471;
  static constexpr Tagged_t allocation_memento_map = 0x2499;
  static constexpr Tagged_t array_boilerplate_description_map = 0x24c1;
  static constexpr Tagged_t asm_wasm_data_map = 0x24e9;
  static constexpr Tagged_t async_generator_request_map = 0x2511;
  static constexpr Tagged_t break_point_map = 0x2539;
  static constexpr Tagged_t break_point_info_map = 0x2561;
  static constexpr Tagged_t call_site_info_map = 0x2589;
  static constexpr Tagged_t class_positions_map = 0x25b1;
  static constexpr Tagged_t debug_info_map = 0x25d9;
  static constexpr Tagged_t enum_cache_map = 0x2601;
  static constexpr Tagged_t error_stack_data_map = 0x2629;
  static constexpr Tagged_t function_template_rare_data_map = 0x2651;
  static constexpr Tagged_t interceptor_info_map = 0x2679;
  static constexpr Tagged_t interpreter_data_map = 0x26a1;
  static constexpr Tagged_t module_request_map = 0x26c9;
  static constexpr Tagged_t promise_capability_map = 0x26f1;
  static constexpr Tagged_t promise_on_stack_map = 0x2719;
  static constexpr Tagged_t promise_reaction_map = 0x2741;
  static constexpr Tagged_t property_descriptor_object_map = 0x2769;
  static constexpr Tagged_t prototype_info_map = 0x2791;
  static constexpr Tagged_t regexp_boilerplate_description_map = 0x27b9;
  static constexpr Tagged_t script_map = 0x27e1;
  static constexpr Tagged_t script_or_module_map = 0x2809;
  static constexpr Tagged_t module_info_entry_map = 0x2831;
  static constexpr Tagged_t stack_frame_info_map = 0x2859;
  static constexpr Tagged_t template_object_description_map = 0x2881;
  static constexpr Tagged_t tuple2_map = 0x28a9;
  static constexpr Tagged_t wasm_exception_tag_map = 0x28d1;
  static constexpr Tagged_t wasm_indirect_function_table_map = 0x28f9;
  static constexpr Tagged_t sloppy_arguments_elements_map = 0x36fd;
  static constexpr Tagged_t descriptor_array_map = 0x21f9;
  static constexpr Tagged_t strong_descriptor_array_map = 0x3725;
  static constexpr Tagged_t uncompiled_data_without_preparse_data_map = 0x32ed;
  static constexpr Tagged_t uncompiled_data_with_preparse_data_map = 0x3315;
  static constexpr Tagged_t uncompiled_data_without_preparse_data_with_job_map =
      0x333d;
  static constexpr Tagged_t uncompiled_data_with_preparse_data_and_job_map =
      0x3365;
  static constexpr Tagged_t on_heap_basic_block_profiler_data_map = 0x338d;
  static constexpr Tagged_t turbofan_bitset_type_map = 0x33b5;
  static constexpr Tagged_t turbofan_union_type_map = 0x33dd;
  static constexpr Tagged_t turbofan_range_type_map = 0x3405;
  static constexpr Tagged_t turbofan_heap_constant_type_map = 0x342d;
  static constexpr Tagged_t turbofan_other_number_constant_type_map = 0x3455;
  static constexpr Tagged_t turboshaft_word32type_map = 0x347d;
  static constexpr Tagged_t turboshaft_word32range_type_map = 0x34a5;
  static constexpr Tagged_t turboshaft_word32set_type_map = 0x374d;
  static constexpr Tagged_t turboshaft_word64type_map = 0x34cd;
  static constexpr Tagged_t turboshaft_word64range_type_map = 0x34f5;
  static constexpr Tagged_t turboshaft_word64set_type_map = 0x3775;
  static constexpr Tagged_t turboshaft_float64type_map = 0x351d;
  static constexpr Tagged_t turboshaft_float64range_type_map = 0x3545;
  static constexpr Tagged_t turboshaft_float64set_type_map = 0x379d;
  static constexpr Tagged_t internal_class_map = 0x356d;
  static constexpr Tagged_t smi_pair_map = 0x3595;
  static constexpr Tagged_t smi_box_map = 0x35bd;
  static constexpr Tagged_t exported_sub_class_base_map = 0x35e5;
  static constexpr Tagged_t exported_sub_class_map = 0x360d;
  static constexpr Tagged_t abstract_internal_class_subclass1_map = 0x3635;
  static constexpr Tagged_t abstract_internal_class_subclass2_map = 0x365d;
  static constexpr Tagged_t internal_class_with_smi_elements_map = 0x37c5;
  static constexpr Tagged_t internal_class_with_struct_elements_map = 0x37ed;
  static constexpr Tagged_t exported_sub_class2_map = 0x3685;
  static constexpr Tagged_t sort_state_map = 0x36ad;
  static constexpr Tagged_t wasm_string_view_iter_map = 0x36d5;
  static constexpr Tagged_t allocation_site_map = 0x2921;
  static constexpr Tagged_t allocation_site_without_weaknext_map = 0x2949;
  static constexpr Tagged_t constructor_string = 0x813d;
  static constexpr Tagged_t next_string = 0x8155;
  static constexpr Tagged_t resolve_string = 0x8165;
  static constexpr Tagged_t then_string = 0x8179;
  static constexpr Tagged_t iterator_symbol = 0x8189;
  static constexpr Tagged_t species_symbol = 0x8199;
  static constexpr Tagged_t is_concat_spreadable_symbol = 0x81a9;
  static constexpr Tagged_t load_handler1_map = 0x2971;
  static constexpr Tagged_t load_handler2_map = 0x2999;
  static constexpr Tagged_t load_handler3_map = 0x29c1;
  static constexpr Tagged_t store_handler0_map = 0x29e9;
  static constexpr Tagged_t store_handler1_map = 0x2a11;
  static constexpr Tagged_t store_handler2_map = 0x2a39;
  static constexpr Tagged_t store_handler3_map = 0x2a61;
};

static constexpr std::array<Tagged_t, 739> StaticReadOnlyRootsPointerTable = {
    kStaticReadOnlyRoot::free_space_map,
    kStaticReadOnlyRoot::one_pointer_filler_map,
    kStaticReadOnlyRoot::two_pointer_filler_map,
    kStaticReadOnlyRoot::uninitialized_value,
    kStaticReadOnlyRoot::undefined_value,
    kStaticReadOnlyRoot::the_hole_value,
    kStaticReadOnlyRoot::null_value,
    kStaticReadOnlyRoot::true_value,
    kStaticReadOnlyRoot::false_value,
    kStaticReadOnlyRoot::empty_string,
    kStaticReadOnlyRoot::meta_map,
    kStaticReadOnlyRoot::byte_array_map,
    kStaticReadOnlyRoot::fixed_array_map,
    kStaticReadOnlyRoot::fixed_cow_array_map,
    kStaticReadOnlyRoot::hash_table_map,
    kStaticReadOnlyRoot::symbol_map,
    kStaticReadOnlyRoot::one_byte_string_map,
    kStaticReadOnlyRoot::one_byte_internalized_string_map,
    kStaticReadOnlyRoot::scope_info_map,
    kStaticReadOnlyRoot::shared_function_info_map,
    kStaticReadOnlyRoot::code_map,
    kStaticReadOnlyRoot::cell_map,
    kStaticReadOnlyRoot::global_property_cell_map,
    kStaticReadOnlyRoot::foreign_map,
    kStaticReadOnlyRoot::heap_number_map,
    kStaticReadOnlyRoot::transition_array_map,
    kStaticReadOnlyRoot::thin_one_byte_string_map,
    kStaticReadOnlyRoot::feedback_vector_map,
    kStaticReadOnlyRoot::empty_scope_info,
    kStaticReadOnlyRoot::empty_fixed_array,
    kStaticReadOnlyRoot::empty_descriptor_array,
    kStaticReadOnlyRoot::arguments_marker,
    kStaticReadOnlyRoot::exception,
    kStaticReadOnlyRoot::termination_exception,
    kStaticReadOnlyRoot::optimized_out,
    kStaticReadOnlyRoot::stale_register,
    kStaticReadOnlyRoot::script_context_table_map,
    kStaticReadOnlyRoot::closure_feedback_cell_array_map,
    kStaticReadOnlyRoot::feedback_metadata_map,
    kStaticReadOnlyRoot::array_list_map,
    kStaticReadOnlyRoot::bigint_map,
    kStaticReadOnlyRoot::object_boilerplate_description_map,
    kStaticReadOnlyRoot::bytecode_array_map,
    kStaticReadOnlyRoot::code_data_container_map,
    kStaticReadOnlyRoot::coverage_info_map,
    kStaticReadOnlyRoot::fixed_double_array_map,
    kStaticReadOnlyRoot::global_dictionary_map,
    kStaticReadOnlyRoot::many_closures_cell_map,
    kStaticReadOnlyRoot::mega_dom_handler_map,
    kStaticReadOnlyRoot::module_info_map,
    kStaticReadOnlyRoot::name_dictionary_map,
    kStaticReadOnlyRoot::no_closures_cell_map,
    kStaticReadOnlyRoot::number_dictionary_map,
    kStaticReadOnlyRoot::one_closure_cell_map,
    kStaticReadOnlyRoot::ordered_hash_map_map,
    kStaticReadOnlyRoot::ordered_hash_set_map,
    kStaticReadOnlyRoot::name_to_index_hash_table_map,
    kStaticReadOnlyRoot::registered_symbol_table_map,
    kStaticReadOnlyRoot::ordered_name_dictionary_map,
    kStaticReadOnlyRoot::preparse_data_map,
    kStaticReadOnlyRoot::property_array_map,
    kStaticReadOnlyRoot::accessor_info_map,
    kStaticReadOnlyRoot::side_effect_call_handler_info_map,
    kStaticReadOnlyRoot::side_effect_free_call_handler_info_map,
    kStaticReadOnlyRoot::next_call_side_effect_free_call_handler_info_map,
    kStaticReadOnlyRoot::simple_number_dictionary_map,
    kStaticReadOnlyRoot::small_ordered_hash_map_map,
    kStaticReadOnlyRoot::small_ordered_hash_set_map,
    kStaticReadOnlyRoot::small_ordered_name_dictionary_map,
    kStaticReadOnlyRoot::source_text_module_map,
    kStaticReadOnlyRoot::swiss_name_dictionary_map,
    kStaticReadOnlyRoot::synthetic_module_map,
    kStaticReadOnlyRoot::wasm_api_function_ref_map,
    kStaticReadOnlyRoot::wasm_capi_function_data_map,
    kStaticReadOnlyRoot::wasm_exported_function_data_map,
    kStaticReadOnlyRoot::wasm_internal_function_map,
    kStaticReadOnlyRoot::wasm_js_function_data_map,
    kStaticReadOnlyRoot::wasm_resume_data_map,
    kStaticReadOnlyRoot::wasm_type_info_map,
    kStaticReadOnlyRoot::wasm_continuation_object_map,
    kStaticReadOnlyRoot::weak_fixed_array_map,
    kStaticReadOnlyRoot::weak_array_list_map,
    kStaticReadOnlyRoot::ephemeron_hash_table_map,
    kStaticReadOnlyRoot::embedder_data_array_map,
    kStaticReadOnlyRoot::weak_cell_map,
    kStaticReadOnlyRoot::string_map,
    kStaticReadOnlyRoot::cons_one_byte_string_map,
    kStaticReadOnlyRoot::cons_string_map,
    kStaticReadOnlyRoot::thin_string_map,
    kStaticReadOnlyRoot::sliced_string_map,
    kStaticReadOnlyRoot::sliced_one_byte_string_map,
    kStaticReadOnlyRoot::external_string_map,
    kStaticReadOnlyRoot::external_one_byte_string_map,
    kStaticReadOnlyRoot::uncached_external_string_map,
    kStaticReadOnlyRoot::internalized_string_map,
    kStaticReadOnlyRoot::external_internalized_string_map,
    kStaticReadOnlyRoot::external_one_byte_internalized_string_map,
    kStaticReadOnlyRoot::uncached_external_internalized_string_map,
    kStaticReadOnlyRoot::uncached_external_one_byte_internalized_string_map,
    kStaticReadOnlyRoot::uncached_external_one_byte_string_map,
    kStaticReadOnlyRoot::shared_one_byte_string_map,
    kStaticReadOnlyRoot::shared_string_map,
    kStaticReadOnlyRoot::shared_external_one_byte_string_map,
    kStaticReadOnlyRoot::shared_external_string_map,
    kStaticReadOnlyRoot::shared_uncached_external_one_byte_string_map,
    kStaticReadOnlyRoot::shared_uncached_external_string_map,
    kStaticReadOnlyRoot::shared_thin_one_byte_string_map,
    kStaticReadOnlyRoot::shared_thin_string_map,
    kStaticReadOnlyRoot::undefined_map,
    kStaticReadOnlyRoot::the_hole_map,
    kStaticReadOnlyRoot::null_map,
    kStaticReadOnlyRoot::boolean_map,
    kStaticReadOnlyRoot::uninitialized_map,
    kStaticReadOnlyRoot::arguments_marker_map,
    kStaticReadOnlyRoot::exception_map,
    kStaticReadOnlyRoot::termination_exception_map,
    kStaticReadOnlyRoot::optimized_out_map,
    kStaticReadOnlyRoot::stale_register_map,
    kStaticReadOnlyRoot::self_reference_marker_map,
    kStaticReadOnlyRoot::basic_block_counters_marker_map,
    kStaticReadOnlyRoot::empty_enum_cache,
    kStaticReadOnlyRoot::empty_property_array,
    kStaticReadOnlyRoot::empty_byte_array,
    kStaticReadOnlyRoot::empty_object_boilerplate_description,
    kStaticReadOnlyRoot::empty_array_boilerplate_description,
    kStaticReadOnlyRoot::empty_closure_feedback_cell_array,
    kStaticReadOnlyRoot::empty_slow_element_dictionary,
    kStaticReadOnlyRoot::empty_ordered_hash_map,
    kStaticReadOnlyRoot::empty_ordered_hash_set,
    kStaticReadOnlyRoot::empty_feedback_metadata,
    kStaticReadOnlyRoot::empty_property_dictionary,
    kStaticReadOnlyRoot::empty_ordered_property_dictionary,
    kStaticReadOnlyRoot::empty_swiss_property_dictionary,
    kStaticReadOnlyRoot::noop_interceptor_info,
    kStaticReadOnlyRoot::empty_array_list,
    kStaticReadOnlyRoot::empty_weak_fixed_array,
    kStaticReadOnlyRoot::empty_weak_array_list,
    kStaticReadOnlyRoot::invalid_prototype_validity_cell,
    kStaticReadOnlyRoot::nan_value,
    kStaticReadOnlyRoot::hole_nan_value,
    kStaticReadOnlyRoot::infinity_value,
    kStaticReadOnlyRoot::minus_zero_value,
    kStaticReadOnlyRoot::minus_infinity_value,
    kStaticReadOnlyRoot::max_safe_integer,
    kStaticReadOnlyRoot::max_uint_32,
    kStaticReadOnlyRoot::smi_min_value,
    kStaticReadOnlyRoot::smi_max_value_plus_one,
    kStaticReadOnlyRoot::single_character_string_table,
    kStaticReadOnlyRoot::self_reference_marker,
    kStaticReadOnlyRoot::basic_block_counters_marker,
    kStaticReadOnlyRoot::off_heap_trampoline_relocation_info,
    kStaticReadOnlyRoot::trampoline_trivial_code_data_container,
    kStaticReadOnlyRoot::trampoline_promise_rejection_code_data_container,
    kStaticReadOnlyRoot::global_this_binding_scope_info,
    kStaticReadOnlyRoot::empty_function_scope_info,
    kStaticReadOnlyRoot::native_scope_info,
    kStaticReadOnlyRoot::shadow_realm_scope_info,
    kStaticReadOnlyRoot::empty_symbol_table,
    kStaticReadOnlyRoot::hash_seed,
    kStaticReadOnlyRoot::adoptText_string,
    kStaticReadOnlyRoot::approximatelySign_string,
    kStaticReadOnlyRoot::baseName_string,
    kStaticReadOnlyRoot::accounting_string,
    kStaticReadOnlyRoot::breakType_string,
    kStaticReadOnlyRoot::calendars_string,
    kStaticReadOnlyRoot::cardinal_string,
    kStaticReadOnlyRoot::caseFirst_string,
    kStaticReadOnlyRoot::ceil_string,
    kStaticReadOnlyRoot::compare_string,
    kStaticReadOnlyRoot::collation_string,
    kStaticReadOnlyRoot::collations_string,
    kStaticReadOnlyRoot::compact_string,
    kStaticReadOnlyRoot::compactDisplay_string,
    kStaticReadOnlyRoot::currency_string,
    kStaticReadOnlyRoot::currencyDisplay_string,
    kStaticReadOnlyRoot::currencySign_string,
    kStaticReadOnlyRoot::dateStyle_string,
    kStaticReadOnlyRoot::dateTimeField_string,
    kStaticReadOnlyRoot::dayPeriod_string,
    kStaticReadOnlyRoot::daysDisplay_string,
    kStaticReadOnlyRoot::decimal_string,
    kStaticReadOnlyRoot::dialect_string,
    kStaticReadOnlyRoot::digital_string,
    kStaticReadOnlyRoot::direction_string,
    kStaticReadOnlyRoot::endRange_string,
    kStaticReadOnlyRoot::engineering_string,
    kStaticReadOnlyRoot::exceptZero_string,
    kStaticReadOnlyRoot::expand_string,
    kStaticReadOnlyRoot::exponentInteger_string,
    kStaticReadOnlyRoot::exponentMinusSign_string,
    kStaticReadOnlyRoot::exponentSeparator_string,
    kStaticReadOnlyRoot::fallback_string,
    kStaticReadOnlyRoot::first_string,
    kStaticReadOnlyRoot::firstDay_string,
    kStaticReadOnlyRoot::floor_string,
    kStaticReadOnlyRoot::format_string,
    kStaticReadOnlyRoot::fraction_string,
    kStaticReadOnlyRoot::fractionalDigits_string,
    kStaticReadOnlyRoot::fractionalSecond_string,
    kStaticReadOnlyRoot::full_string,
    kStaticReadOnlyRoot::granularity_string,
    kStaticReadOnlyRoot::grapheme_string,
    kStaticReadOnlyRoot::group_string,
    kStaticReadOnlyRoot::h11_string,
    kStaticReadOnlyRoot::h12_string,
    kStaticReadOnlyRoot::h23_string,
    kStaticReadOnlyRoot::h24_string,
    kStaticReadOnlyRoot::halfCeil_string,
    kStaticReadOnlyRoot::halfEven_string,
    kStaticReadOnlyRoot::halfExpand_string,
    kStaticReadOnlyRoot::halfFloor_string,
    kStaticReadOnlyRoot::halfTrunc_string,
    kStaticReadOnlyRoot::hour12_string,
    kStaticReadOnlyRoot::hourCycle_string,
    kStaticReadOnlyRoot::hourCycles_string,
    kStaticReadOnlyRoot::hoursDisplay_string,
    kStaticReadOnlyRoot::ideo_string,
    kStaticReadOnlyRoot::ignorePunctuation_string,
    kStaticReadOnlyRoot::Invalid_Date_string,
    kStaticReadOnlyRoot::integer_string,
    kStaticReadOnlyRoot::isWordLike_string,
    kStaticReadOnlyRoot::kana_string,
    kStaticReadOnlyRoot::language_string,
    kStaticReadOnlyRoot::languageDisplay_string,
    kStaticReadOnlyRoot::lessPrecision_string,
    kStaticReadOnlyRoot::letter_string,
    kStaticReadOnlyRoot::list_string,
    kStaticReadOnlyRoot::literal_string,
    kStaticReadOnlyRoot::locale_string,
    kStaticReadOnlyRoot::loose_string,
    kStaticReadOnlyRoot::lower_string,
    kStaticReadOnlyRoot::ltr_string,
    kStaticReadOnlyRoot::maximumFractionDigits_string,
    kStaticReadOnlyRoot::maximumSignificantDigits_string,
    kStaticReadOnlyRoot::microsecondsDisplay_string,
    kStaticReadOnlyRoot::millisecondsDisplay_string,
    kStaticReadOnlyRoot::min2_string,
    kStaticReadOnlyRoot::minimalDays_string,
    kStaticReadOnlyRoot::minimumFractionDigits_string,
    kStaticReadOnlyRoot::minimumIntegerDigits_string,
    kStaticReadOnlyRoot::minimumSignificantDigits_string,
    kStaticReadOnlyRoot::minus_0,
    kStaticReadOnlyRoot::minusSign_string,
    kStaticReadOnlyRoot::minutesDisplay_string,
    kStaticReadOnlyRoot::monthsDisplay_string,
    kStaticReadOnlyRoot::morePrecision_string,
    kStaticReadOnlyRoot::nan_string,
    kStaticReadOnlyRoot::nanosecondsDisplay_string,
    kStaticReadOnlyRoot::narrowSymbol_string,
    kStaticReadOnlyRoot::negative_string,
    kStaticReadOnlyRoot::never_string,
    kStaticReadOnlyRoot::none_string,
    kStaticReadOnlyRoot::notation_string,
    kStaticReadOnlyRoot::normal_string,
    kStaticReadOnlyRoot::numberingSystem_string,
    kStaticReadOnlyRoot::numberingSystems_string,
    kStaticReadOnlyRoot::numeric_string,
    kStaticReadOnlyRoot::ordinal_string,
    kStaticReadOnlyRoot::percentSign_string,
    kStaticReadOnlyRoot::plusSign_string,
    kStaticReadOnlyRoot::quarter_string,
    kStaticReadOnlyRoot::region_string,
    kStaticReadOnlyRoot::relatedYear_string,
    kStaticReadOnlyRoot::roundingMode_string,
    kStaticReadOnlyRoot::roundingPriority_string,
    kStaticReadOnlyRoot::rtl_string,
    kStaticReadOnlyRoot::scientific_string,
    kStaticReadOnlyRoot::secondsDisplay_string,
    kStaticReadOnlyRoot::segment_string,
    kStaticReadOnlyRoot::SegmentIterator_string,
    kStaticReadOnlyRoot::Segments_string,
    kStaticReadOnlyRoot::sensitivity_string,
    kStaticReadOnlyRoot::sep_string,
    kStaticReadOnlyRoot::shared_string,
    kStaticReadOnlyRoot::signDisplay_string,
    kStaticReadOnlyRoot::standard_string,
    kStaticReadOnlyRoot::startRange_string,
    kStaticReadOnlyRoot::strict_string,
    kStaticReadOnlyRoot::stripIfInteger_string,
    kStaticReadOnlyRoot::style_string,
    kStaticReadOnlyRoot::term_string,
    kStaticReadOnlyRoot::textInfo_string,
    kStaticReadOnlyRoot::timeStyle_string,
    kStaticReadOnlyRoot::timeZones_string,
    kStaticReadOnlyRoot::timeZoneName_string,
    kStaticReadOnlyRoot::trailingZeroDisplay_string,
    kStaticReadOnlyRoot::trunc_string,
    kStaticReadOnlyRoot::two_digit_string,
    kStaticReadOnlyRoot::type_string,
    kStaticReadOnlyRoot::unknown_string,
    kStaticReadOnlyRoot::upper_string,
    kStaticReadOnlyRoot::usage_string,
    kStaticReadOnlyRoot::useGrouping_string,
    kStaticReadOnlyRoot::unitDisplay_string,
    kStaticReadOnlyRoot::weekday_string,
    kStaticReadOnlyRoot::weekend_string,
    kStaticReadOnlyRoot::weeksDisplay_string,
    kStaticReadOnlyRoot::weekInfo_string,
    kStaticReadOnlyRoot::yearName_string,
    kStaticReadOnlyRoot::yearsDisplay_string,
    kStaticReadOnlyRoot::add_string,
    kStaticReadOnlyRoot::AggregateError_string,
    kStaticReadOnlyRoot::always_string,
    kStaticReadOnlyRoot::anonymous_function_string,
    kStaticReadOnlyRoot::anonymous_string,
    kStaticReadOnlyRoot::apply_string,
    kStaticReadOnlyRoot::Arguments_string,
    kStaticReadOnlyRoot::arguments_string,
    kStaticReadOnlyRoot::arguments_to_string,
    kStaticReadOnlyRoot::Array_string,
    kStaticReadOnlyRoot::array_to_string,
    kStaticReadOnlyRoot::ArrayBuffer_string,
    kStaticReadOnlyRoot::ArrayIterator_string,
    kStaticReadOnlyRoot::as_string,
    kStaticReadOnlyRoot::assert_string,
    kStaticReadOnlyRoot::async_string,
    kStaticReadOnlyRoot::AtomicsCondition_string,
    kStaticReadOnlyRoot::AtomicsMutex_string,
    kStaticReadOnlyRoot::auto_string,
    kStaticReadOnlyRoot::await_string,
    kStaticReadOnlyRoot::BigInt_string,
    kStaticReadOnlyRoot::bigint_string,
    kStaticReadOnlyRoot::BigInt64Array_string,
    kStaticReadOnlyRoot::BigUint64Array_string,
    kStaticReadOnlyRoot::bind_string,
    kStaticReadOnlyRoot::blank_string,
    kStaticReadOnlyRoot::Boolean_string,
    kStaticReadOnlyRoot::boolean_string,
    kStaticReadOnlyRoot::boolean_to_string,
    kStaticReadOnlyRoot::bound__string,
    kStaticReadOnlyRoot::buffer_string,
    kStaticReadOnlyRoot::byte_length_string,
    kStaticReadOnlyRoot::byte_offset_string,
    kStaticReadOnlyRoot::CompileError_string,
    kStaticReadOnlyRoot::calendar_string,
    kStaticReadOnlyRoot::callee_string,
    kStaticReadOnlyRoot::caller_string,
    kStaticReadOnlyRoot::cause_string,
    kStaticReadOnlyRoot::character_string,
    kStaticReadOnlyRoot::closure_string,
    kStaticReadOnlyRoot::code_string,
    kStaticReadOnlyRoot::column_string,
    kStaticReadOnlyRoot::computed_string,
    kStaticReadOnlyRoot::configurable_string,
    kStaticReadOnlyRoot::conjunction_string,
    kStaticReadOnlyRoot::console_string,
    kStaticReadOnlyRoot::constrain_string,
    kStaticReadOnlyRoot::construct_string,
    kStaticReadOnlyRoot::current_string,
    kStaticReadOnlyRoot::Date_string,
    kStaticReadOnlyRoot::date_to_string,
    kStaticReadOnlyRoot::dateAdd_string,
    kStaticReadOnlyRoot::dateFromFields_string,
    kStaticReadOnlyRoot::dateUntil_string,
    kStaticReadOnlyRoot::day_string,
    kStaticReadOnlyRoot::dayOfWeek_string,
    kStaticReadOnlyRoot::dayOfYear_string,
    kStaticReadOnlyRoot::days_string,
    kStaticReadOnlyRoot::daysInMonth_string,
    kStaticReadOnlyRoot::daysInWeek_string,
    kStaticReadOnlyRoot::daysInYear_string,
    kStaticReadOnlyRoot::default_string,
    kStaticReadOnlyRoot::defineProperty_string,
    kStaticReadOnlyRoot::deleteProperty_string,
    kStaticReadOnlyRoot::disjunction_string,
    kStaticReadOnlyRoot::done_string,
    kStaticReadOnlyRoot::dot_brand_string,
    kStaticReadOnlyRoot::dot_catch_string,
    kStaticReadOnlyRoot::dot_default_string,
    kStaticReadOnlyRoot::dot_for_string,
    kStaticReadOnlyRoot::dot_generator_object_string,
    kStaticReadOnlyRoot::dot_home_object_string,
    kStaticReadOnlyRoot::dot_new_target_string,
    kStaticReadOnlyRoot::dot_result_string,
    kStaticReadOnlyRoot::dot_repl_result_string,
    kStaticReadOnlyRoot::dot_static_home_object_string,
    kStaticReadOnlyRoot::dot_string,
    kStaticReadOnlyRoot::dot_switch_tag_string,
    kStaticReadOnlyRoot::dotAll_string,
    kStaticReadOnlyRoot::Error_string,
    kStaticReadOnlyRoot::EvalError_string,
    kStaticReadOnlyRoot::enumerable_string,
    kStaticReadOnlyRoot::element_string,
    kStaticReadOnlyRoot::epochMicroseconds_string,
    kStaticReadOnlyRoot::epochMilliseconds_string,
    kStaticReadOnlyRoot::epochNanoseconds_string,
    kStaticReadOnlyRoot::epochSeconds_string,
    kStaticReadOnlyRoot::era_string,
    kStaticReadOnlyRoot::eraYear_string,
    kStaticReadOnlyRoot::errors_string,
    kStaticReadOnlyRoot::error_to_string,
    kStaticReadOnlyRoot::eval_string,
    kStaticReadOnlyRoot::exception_string,
    kStaticReadOnlyRoot::exec_string,
    kStaticReadOnlyRoot::false_string,
    kStaticReadOnlyRoot::fields_string,
    kStaticReadOnlyRoot::FinalizationRegistry_string,
    kStaticReadOnlyRoot::flags_string,
    kStaticReadOnlyRoot::Float32Array_string,
    kStaticReadOnlyRoot::Float64Array_string,
    kStaticReadOnlyRoot::fractionalSecondDigits_string,
    kStaticReadOnlyRoot::from_string,
    kStaticReadOnlyRoot::Function_string,
    kStaticReadOnlyRoot::function_native_code_string,
    kStaticReadOnlyRoot::function_string,
    kStaticReadOnlyRoot::function_to_string,
    kStaticReadOnlyRoot::Generator_string,
    kStaticReadOnlyRoot::get_space_string,
    kStaticReadOnlyRoot::get_string,
    kStaticReadOnlyRoot::getOffsetNanosecondsFor_string,
    kStaticReadOnlyRoot::getOwnPropertyDescriptor_string,
    kStaticReadOnlyRoot::getPossibleInstantsFor_string,
    kStaticReadOnlyRoot::getPrototypeOf_string,
    kStaticReadOnlyRoot::global_string,
    kStaticReadOnlyRoot::globalThis_string,
    kStaticReadOnlyRoot::groups_string,
    kStaticReadOnlyRoot::growable_string,
    kStaticReadOnlyRoot::has_string,
    kStaticReadOnlyRoot::hasIndices_string,
    kStaticReadOnlyRoot::hour_string,
    kStaticReadOnlyRoot::hours_string,
    kStaticReadOnlyRoot::hoursInDay_string,
    kStaticReadOnlyRoot::ignoreCase_string,
    kStaticReadOnlyRoot::id_string,
    kStaticReadOnlyRoot::illegal_access_string,
    kStaticReadOnlyRoot::illegal_argument_string,
    kStaticReadOnlyRoot::inLeapYear_string,
    kStaticReadOnlyRoot::index_string,
    kStaticReadOnlyRoot::indices_string,
    kStaticReadOnlyRoot::Infinity_string,
    kStaticReadOnlyRoot::infinity_string,
    kStaticReadOnlyRoot::input_string,
    kStaticReadOnlyRoot::Int16Array_string,
    kStaticReadOnlyRoot::Int32Array_string,
    kStaticReadOnlyRoot::Int8Array_string,
    kStaticReadOnlyRoot::isExtensible_string,
    kStaticReadOnlyRoot::iso8601_string,
    kStaticReadOnlyRoot::isoDay_string,
    kStaticReadOnlyRoot::isoHour_string,
    kStaticReadOnlyRoot::isoMicrosecond_string,
    kStaticReadOnlyRoot::isoMillisecond_string,
    kStaticReadOnlyRoot::isoMinute_string,
    kStaticReadOnlyRoot::isoMonth_string,
    kStaticReadOnlyRoot::isoNanosecond_string,
    kStaticReadOnlyRoot::isoSecond_string,
    kStaticReadOnlyRoot::isoYear_string,
    kStaticReadOnlyRoot::jsMemoryEstimate_string,
    kStaticReadOnlyRoot::jsMemoryRange_string,
    kStaticReadOnlyRoot::keys_string,
    kStaticReadOnlyRoot::largestUnit_string,
    kStaticReadOnlyRoot::lastIndex_string,
    kStaticReadOnlyRoot::length_string,
    kStaticReadOnlyRoot::let_string,
    kStaticReadOnlyRoot::line_string,
    kStaticReadOnlyRoot::linear_string,
    kStaticReadOnlyRoot::LinkError_string,
    kStaticReadOnlyRoot::long_string,
    kStaticReadOnlyRoot::Map_string,
    kStaticReadOnlyRoot::MapIterator_string,
    kStaticReadOnlyRoot::max_byte_length_string,
    kStaticReadOnlyRoot::medium_string,
    kStaticReadOnlyRoot::mergeFields_string,
    kStaticReadOnlyRoot::message_string,
    kStaticReadOnlyRoot::meta_string,
    kStaticReadOnlyRoot::minus_Infinity_string,
    kStaticReadOnlyRoot::microsecond_string,
    kStaticReadOnlyRoot::microseconds_string,
    kStaticReadOnlyRoot::millisecond_string,
    kStaticReadOnlyRoot::milliseconds_string,
    kStaticReadOnlyRoot::minute_string,
    kStaticReadOnlyRoot::minutes_string,
    kStaticReadOnlyRoot::Module_string,
    kStaticReadOnlyRoot::month_string,
    kStaticReadOnlyRoot::monthDayFromFields_string,
    kStaticReadOnlyRoot::months_string,
    kStaticReadOnlyRoot::monthsInYear_string,
    kStaticReadOnlyRoot::monthCode_string,
    kStaticReadOnlyRoot::multiline_string,
    kStaticReadOnlyRoot::name_string,
    kStaticReadOnlyRoot::NaN_string,
    kStaticReadOnlyRoot::nanosecond_string,
    kStaticReadOnlyRoot::nanoseconds_string,
    kStaticReadOnlyRoot::narrow_string,
    kStaticReadOnlyRoot::native_string,
    kStaticReadOnlyRoot::new_target_string,
    kStaticReadOnlyRoot::NFC_string,
    kStaticReadOnlyRoot::NFD_string,
    kStaticReadOnlyRoot::NFKC_string,
    kStaticReadOnlyRoot::NFKD_string,
    kStaticReadOnlyRoot::not_equal_string,
    kStaticReadOnlyRoot::null_string,
    kStaticReadOnlyRoot::null_to_string,
    kStaticReadOnlyRoot::Number_string,
    kStaticReadOnlyRoot::number_string,
    kStaticReadOnlyRoot::number_to_string,
    kStaticReadOnlyRoot::Object_string,
    kStaticReadOnlyRoot::object_string,
    kStaticReadOnlyRoot::object_to_string,
    kStaticReadOnlyRoot::of_string,
    kStaticReadOnlyRoot::offset_string,
    kStaticReadOnlyRoot::offsetNanoseconds_string,
    kStaticReadOnlyRoot::ok_string,
    kStaticReadOnlyRoot::one_string,
    kStaticReadOnlyRoot::other_string,
    kStaticReadOnlyRoot::overflow_string,
    kStaticReadOnlyRoot::ownKeys_string,
    kStaticReadOnlyRoot::percent_string,
    kStaticReadOnlyRoot::plainDate_string,
    kStaticReadOnlyRoot::plainTime_string,
    kStaticReadOnlyRoot::position_string,
    kStaticReadOnlyRoot::preventExtensions_string,
    kStaticReadOnlyRoot::private_constructor_string,
    kStaticReadOnlyRoot::Promise_string,
    kStaticReadOnlyRoot::proto_string,
    kStaticReadOnlyRoot::prototype_string,
    kStaticReadOnlyRoot::proxy_string,
    kStaticReadOnlyRoot::Proxy_string,
    kStaticReadOnlyRoot::query_colon_string,
    kStaticReadOnlyRoot::RangeError_string,
    kStaticReadOnlyRoot::raw_json_string,
    kStaticReadOnlyRoot::raw_string,
    kStaticReadOnlyRoot::ReferenceError_string,
    kStaticReadOnlyRoot::ReflectGet_string,
    kStaticReadOnlyRoot::ReflectHas_string,
    kStaticReadOnlyRoot::RegExp_string,
    kStaticReadOnlyRoot::regexp_to_string,
    kStaticReadOnlyRoot::reject_string,
    kStaticReadOnlyRoot::relativeTo_string,
    kStaticReadOnlyRoot::resizable_string,
    kStaticReadOnlyRoot::ResizableArrayBuffer_string,
    kStaticReadOnlyRoot::return_string,
    kStaticReadOnlyRoot::revoke_string,
    kStaticReadOnlyRoot::roundingIncrement_string,
    kStaticReadOnlyRoot::RuntimeError_string,
    kStaticReadOnlyRoot::WebAssemblyException_string,
    kStaticReadOnlyRoot::Script_string,
    kStaticReadOnlyRoot::script_string,
    kStaticReadOnlyRoot::second_string,
    kStaticReadOnlyRoot::seconds_string,
    kStaticReadOnlyRoot::short_string,
    kStaticReadOnlyRoot::Set_string,
    kStaticReadOnlyRoot::sentence_string,
    kStaticReadOnlyRoot::set_space_string,
    kStaticReadOnlyRoot::set_string,
    kStaticReadOnlyRoot::SetIterator_string,
    kStaticReadOnlyRoot::setPrototypeOf_string,
    kStaticReadOnlyRoot::ShadowRealm_string,
    kStaticReadOnlyRoot::SharedArray_string,
    kStaticReadOnlyRoot::SharedArrayBuffer_string,
    kStaticReadOnlyRoot::SharedStruct_string,
    kStaticReadOnlyRoot::sign_string,
    kStaticReadOnlyRoot::smallestUnit_string,
    kStaticReadOnlyRoot::source_string,
    kStaticReadOnlyRoot::sourceText_string,
    kStaticReadOnlyRoot::stack_string,
    kStaticReadOnlyRoot::stackTraceLimit_string,
    kStaticReadOnlyRoot::sticky_string,
    kStaticReadOnlyRoot::String_string,
    kStaticReadOnlyRoot::string_string,
    kStaticReadOnlyRoot::string_to_string,
    kStaticReadOnlyRoot::Symbol_iterator_string,
    kStaticReadOnlyRoot::symbol_species_string,
    kStaticReadOnlyRoot::Symbol_species_string,
    kStaticReadOnlyRoot::Symbol_string,
    kStaticReadOnlyRoot::symbol_string,
    kStaticReadOnlyRoot::SyntaxError_string,
    kStaticReadOnlyRoot::target_string,
    kStaticReadOnlyRoot::this_function_string,
    kStaticReadOnlyRoot::this_string,
    kStaticReadOnlyRoot::throw_string,
    kStaticReadOnlyRoot::timed_out_string,
    kStaticReadOnlyRoot::timeZone_string,
    kStaticReadOnlyRoot::toJSON_string,
    kStaticReadOnlyRoot::toString_string,
    kStaticReadOnlyRoot::true_string,
    kStaticReadOnlyRoot::total_string,
    kStaticReadOnlyRoot::TypeError_string,
    kStaticReadOnlyRoot::Uint16Array_string,
    kStaticReadOnlyRoot::Uint32Array_string,
    kStaticReadOnlyRoot::Uint8Array_string,
    kStaticReadOnlyRoot::Uint8ClampedArray_string,
    kStaticReadOnlyRoot::undefined_string,
    kStaticReadOnlyRoot::undefined_to_string,
    kStaticReadOnlyRoot::unicode_string,
    kStaticReadOnlyRoot::unicodeSets_string,
    kStaticReadOnlyRoot::unit_string,
    kStaticReadOnlyRoot::URIError_string,
    kStaticReadOnlyRoot::UTC_string,
    kStaticReadOnlyRoot::value_string,
    kStaticReadOnlyRoot::valueOf_string,
    kStaticReadOnlyRoot::WeakMap_string,
    kStaticReadOnlyRoot::WeakRef_string,
    kStaticReadOnlyRoot::WeakSet_string,
    kStaticReadOnlyRoot::week_string,
    kStaticReadOnlyRoot::weeks_string,
    kStaticReadOnlyRoot::weekOfYear_string,
    kStaticReadOnlyRoot::word_string,
    kStaticReadOnlyRoot::writable_string,
    kStaticReadOnlyRoot::yearMonthFromFields_string,
    kStaticReadOnlyRoot::year_string,
    kStaticReadOnlyRoot::years_string,
    kStaticReadOnlyRoot::zero_string,
    kStaticReadOnlyRoot::array_buffer_wasm_memory_symbol,
    kStaticReadOnlyRoot::call_site_info_symbol,
    kStaticReadOnlyRoot::console_context_id_symbol,
    kStaticReadOnlyRoot::console_context_name_symbol,
    kStaticReadOnlyRoot::class_fields_symbol,
    kStaticReadOnlyRoot::class_positions_symbol,
    kStaticReadOnlyRoot::elements_transition_symbol,
    kStaticReadOnlyRoot::error_end_pos_symbol,
    kStaticReadOnlyRoot::error_script_symbol,
    kStaticReadOnlyRoot::error_stack_symbol,
    kStaticReadOnlyRoot::error_start_pos_symbol,
    kStaticReadOnlyRoot::frozen_symbol,
    kStaticReadOnlyRoot::interpreter_trampoline_symbol,
    kStaticReadOnlyRoot::mega_dom_symbol,
    kStaticReadOnlyRoot::megamorphic_symbol,
    kStaticReadOnlyRoot::native_context_index_symbol,
    kStaticReadOnlyRoot::nonextensible_symbol,
    kStaticReadOnlyRoot::not_mapped_symbol,
    kStaticReadOnlyRoot::promise_debug_marker_symbol,
    kStaticReadOnlyRoot::promise_debug_message_symbol,
    kStaticReadOnlyRoot::promise_forwarding_handler_symbol,
    kStaticReadOnlyRoot::promise_handled_by_symbol,
    kStaticReadOnlyRoot::promise_awaited_by_symbol,
    kStaticReadOnlyRoot::regexp_result_names_symbol,
    kStaticReadOnlyRoot::regexp_result_regexp_input_symbol,
    kStaticReadOnlyRoot::regexp_result_regexp_last_index_symbol,
    kStaticReadOnlyRoot::sealed_symbol,
    kStaticReadOnlyRoot::strict_function_transition_symbol,
    kStaticReadOnlyRoot::template_literal_function_literal_id_symbol,
    kStaticReadOnlyRoot::template_literal_slot_id_symbol,
    kStaticReadOnlyRoot::wasm_exception_tag_symbol,
    kStaticReadOnlyRoot::wasm_exception_values_symbol,
    kStaticReadOnlyRoot::wasm_uncatchable_symbol,
    kStaticReadOnlyRoot::wasm_wrapped_object_symbol,
    kStaticReadOnlyRoot::wasm_debug_proxy_cache_symbol,
    kStaticReadOnlyRoot::wasm_debug_proxy_names_symbol,
    kStaticReadOnlyRoot::uninitialized_symbol,
    kStaticReadOnlyRoot::async_iterator_symbol,
    kStaticReadOnlyRoot::intl_fallback_symbol,
    kStaticReadOnlyRoot::match_all_symbol,
    kStaticReadOnlyRoot::match_symbol,
    kStaticReadOnlyRoot::replace_symbol,
    kStaticReadOnlyRoot::search_symbol,
    kStaticReadOnlyRoot::split_symbol,
    kStaticReadOnlyRoot::to_primitive_symbol,
    kStaticReadOnlyRoot::unscopables_symbol,
    kStaticReadOnlyRoot::has_instance_symbol,
    kStaticReadOnlyRoot::to_string_tag_symbol,
    kStaticReadOnlyRoot::promise_fulfill_reaction_job_task_map,
    kStaticReadOnlyRoot::promise_reject_reaction_job_task_map,
    kStaticReadOnlyRoot::callable_task_map,
    kStaticReadOnlyRoot::callback_task_map,
    kStaticReadOnlyRoot::promise_resolve_thenable_job_task_map,
    kStaticReadOnlyRoot::function_template_info_map,
    kStaticReadOnlyRoot::object_template_info_map,
    kStaticReadOnlyRoot::access_check_info_map,
    kStaticReadOnlyRoot::accessor_pair_map,
    kStaticReadOnlyRoot::aliased_arguments_entry_map,
    kStaticReadOnlyRoot::allocation_memento_map,
    kStaticReadOnlyRoot::array_boilerplate_description_map,
    kStaticReadOnlyRoot::asm_wasm_data_map,
    kStaticReadOnlyRoot::async_generator_request_map,
    kStaticReadOnlyRoot::break_point_map,
    kStaticReadOnlyRoot::break_point_info_map,
    kStaticReadOnlyRoot::call_site_info_map,
    kStaticReadOnlyRoot::class_positions_map,
    kStaticReadOnlyRoot::debug_info_map,
    kStaticReadOnlyRoot::enum_cache_map,
    kStaticReadOnlyRoot::error_stack_data_map,
    kStaticReadOnlyRoot::function_template_rare_data_map,
    kStaticReadOnlyRoot::interceptor_info_map,
    kStaticReadOnlyRoot::interpreter_data_map,
    kStaticReadOnlyRoot::module_request_map,
    kStaticReadOnlyRoot::promise_capability_map,
    kStaticReadOnlyRoot::promise_on_stack_map,
    kStaticReadOnlyRoot::promise_reaction_map,
    kStaticReadOnlyRoot::property_descriptor_object_map,
    kStaticReadOnlyRoot::prototype_info_map,
    kStaticReadOnlyRoot::regexp_boilerplate_description_map,
    kStaticReadOnlyRoot::script_map,
    kStaticReadOnlyRoot::script_or_module_map,
    kStaticReadOnlyRoot::module_info_entry_map,
    kStaticReadOnlyRoot::stack_frame_info_map,
    kStaticReadOnlyRoot::template_object_description_map,
    kStaticReadOnlyRoot::tuple2_map,
    kStaticReadOnlyRoot::wasm_exception_tag_map,
    kStaticReadOnlyRoot::wasm_indirect_function_table_map,
    kStaticReadOnlyRoot::sloppy_arguments_elements_map,
    kStaticReadOnlyRoot::descriptor_array_map,
    kStaticReadOnlyRoot::strong_descriptor_array_map,
    kStaticReadOnlyRoot::uncompiled_data_without_preparse_data_map,
    kStaticReadOnlyRoot::uncompiled_data_with_preparse_data_map,
    kStaticReadOnlyRoot::uncompiled_data_without_preparse_data_with_job_map,
    kStaticReadOnlyRoot::uncompiled_data_with_preparse_data_and_job_map,
    kStaticReadOnlyRoot::on_heap_basic_block_profiler_data_map,
    kStaticReadOnlyRoot::turbofan_bitset_type_map,
    kStaticReadOnlyRoot::turbofan_union_type_map,
    kStaticReadOnlyRoot::turbofan_range_type_map,
    kStaticReadOnlyRoot::turbofan_heap_constant_type_map,
    kStaticReadOnlyRoot::turbofan_other_number_constant_type_map,
    kStaticReadOnlyRoot::turboshaft_word32type_map,
    kStaticReadOnlyRoot::turboshaft_word32range_type_map,
    kStaticReadOnlyRoot::turboshaft_word32set_type_map,
    kStaticReadOnlyRoot::turboshaft_word64type_map,
    kStaticReadOnlyRoot::turboshaft_word64range_type_map,
    kStaticReadOnlyRoot::turboshaft_word64set_type_map,
    kStaticReadOnlyRoot::turboshaft_float64type_map,
    kStaticReadOnlyRoot::turboshaft_float64range_type_map,
    kStaticReadOnlyRoot::turboshaft_float64set_type_map,
    kStaticReadOnlyRoot::internal_class_map,
    kStaticReadOnlyRoot::smi_pair_map,
    kStaticReadOnlyRoot::smi_box_map,
    kStaticReadOnlyRoot::exported_sub_class_base_map,
    kStaticReadOnlyRoot::exported_sub_class_map,
    kStaticReadOnlyRoot::abstract_internal_class_subclass1_map,
    kStaticReadOnlyRoot::abstract_internal_class_subclass2_map,
    kStaticReadOnlyRoot::internal_class_with_smi_elements_map,
    kStaticReadOnlyRoot::internal_class_with_struct_elements_map,
    kStaticReadOnlyRoot::exported_sub_class2_map,
    kStaticReadOnlyRoot::sort_state_map,
    kStaticReadOnlyRoot::wasm_string_view_iter_map,
    kStaticReadOnlyRoot::allocation_site_map,
    kStaticReadOnlyRoot::allocation_site_without_weaknext_map,
    kStaticReadOnlyRoot::constructor_string,
    kStaticReadOnlyRoot::next_string,
    kStaticReadOnlyRoot::resolve_string,
    kStaticReadOnlyRoot::then_string,
    kStaticReadOnlyRoot::iterator_symbol,
    kStaticReadOnlyRoot::species_symbol,
    kStaticReadOnlyRoot::is_concat_spreadable_symbol,
    kStaticReadOnlyRoot::load_handler1_map,
    kStaticReadOnlyRoot::load_handler2_map,
    kStaticReadOnlyRoot::load_handler3_map,
    kStaticReadOnlyRoot::store_handler0_map,
    kStaticReadOnlyRoot::store_handler1_map,
    kStaticReadOnlyRoot::store_handler2_map,
    kStaticReadOnlyRoot::store_handler3_map,
};

}  // namespace internal
}  // namespace v8
#endif  // V8_STATIC_ROOTS_BOOL
#endif  // V8_ROOTS_STATIC_ROOTS_H_
