// Copyright 2016 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// The following test is generated by
// https://clusterfuzz.com/testcase?key=5662345442099200
// except the first line of "function gc() {};"
function gc() {};
function __getProperties(obj) {
  let properties = [];
  for (let name of Object.getOwnPropertyNames(obj)) {
 properties.push(name);
  }
  let proto = Object.getPrototypeOf(obj);
  while (proto && proto != Object.prototype) {
proto.forEach();
  }
  return properties;
}
function __getRandomProperty(obj, seed) {
  let properties = __getProperties(obj);
  return properties[seed % properties.length];
}
    new class {
    }()
var __v_106268 = new Proxy({
  year: "numeric",
  hour: "numeric"
},{
  get(__v_106270, __v_106271, __v_106272) {
 try {
      Object.defineProperty(__v_106272, __getRandomProperty(__v_106272, 918631), {
        get: function () {
            delete __v_106272[__getRandomProperty(__v_106272, 205335)], gc();
        }
      });
    } catch (e) {}
    return Reflect.get(__v_106270, __v_106271);
  }
});
  new Intl.DateTimeFormat(undefined, __v_106268);
